apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: music-assistant
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`music.x.pmcd.io`)
      kind: Rule
      services:
        - name: music-assistant
          port: 80
  tls:
    certResolver: pmcdio