# whoami-ingressroute.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: agregarr
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`agregar.x.pmcd.io`)
      kind: Rule
      services:
        - name: agregarr
          port: 80