apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agregarr
  namespace: media
  annotations:
    kubernetes.io/ingress.class: caddy
spec:
  rules:
    - host: agregarr.kube.pmcd.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agregarr
                port:
                  number: 80