apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - storage.yaml

images:
  - name: agregar
    newName: agregarr/agregarr
    newTag: 1.4.2
