apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tautulli
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tautulli.x.pmcd.io`)
      kind: Rule
      services:
        - name: tautulli
          port: 80
  tls:
    certResolver: pmcdio