apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cronjob.yaml
  - storage.yaml

images:
  - name: kometa
    newName: registry.gitlab.com/linuxserver.io/docker-kometa/kometa
    newTag: 2.2.2
