apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: readflow
    app.kubernetes.io/name: readflow
  name: readflow
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: readflow
    app.kubernetes.io/name: readflow
  type: ClusterIP
