apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lidarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`lidarr.x.pmcd.io`)
      kind: Rule
      services:
        - name: lidarr
          port: 80
  tls:
    certResolver: pmcdio