apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtubedl
  labels:
    app.kubernetes.io/instance: youtubedl
    app.kubernetes.io/name: youtubedl
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: youtubedl
      app.kubernetes.io/name: youtubedl
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: youtubedl
        app.kubernetes.io/name: youtubedl
    spec:
      containers:
        - name: youtubedl-material
          image: youtubedl
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: youtubedl-config
          ports:
            - name: http
              containerPort: 17442
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/appdata
            - name: media
              mountPath: /app/video
              subPath: video/youtube/Incoming
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
          resources:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 0.1
              memory: 128Mi
        - name: postprocessor
          image: python:3.12-slim
          env:
            - name: STABLE_SECONDS
              value: "15"
            - name: UNKNOWN_ARTIST
              value: "Unknown Artist"
            - name: COPY_MODE
              value: "0"
          command: [ "sh","-lc" ]
          args:
            - >
              pip install --no-cache-dir watchdog &&
              python /app/watcher.py
          volumeMounts:
            - name: media
              mountPath: /incoming
              subPath: video/youtube/Incoming
            - name: media
              mountPath: /organized
              subPath: video/youtube/Organized
            - name: script
              mountPath: /app/watcher.py
              subPath: watcher.py
              readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: longhorn-youtubedl-config
        - name: media
          persistentVolumeClaim:
            claimName: smb-media-claim
        - name: script
          configMap:
            name: ytdl-postprocessor-script