apiVersion: v1
kind: Service
metadata:
  name: youtubedl
  labels:
    app.kubernetes.io/instance: youtubedl
    app.kubernetes.io/name: youtubedl
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: youtubedl
    app.kubernetes.io/instance: youtubedl