apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: notifiarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`notifiarr.x.pmcd.io`)
      kind: Rule
      services:
        - name: notifiarr
          port: 80
  tls:
    certResolver: pmcdio