apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - pvc.yaml

images:
  - name: ersatztv
    newName: jasongdove/ersatztv
    newTag: v0.8.9-vaapi
