apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - pvc.yaml

images:
  - name: ersatztv
    newName: ghcr.io/ersatztv/ersatztv:latest
    newTag: v26.1.1
