apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - 1password.secret.yaml
  - storage.yaml
  - celery.statefulset.yaml

images:
  - name: dispatcharr
    newName: patrickjmcd/dispatcharr
    newTag: celery-numpy-test
#    newName: ghcr.io/dispatcharr/dispatcharr
#    newTag: 0.19.0
