apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: dispatcharr
    app.kubernetes.io/name: dispatcharr
  name: dispatcharr
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: dispatcharr
    app.kubernetes.io/name: dispatcharr
  type: ClusterIP
