apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: prometheus
    name: in-cluster
  project: core-components
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  sources:
    - path: core/prometheus-assets
      repoURL: https://github.com/patrickjmcd/k8s-argo.git
      targetRevision: main
    - repoURL: https://github.com/patrickjmcd/k8s-argo.git
      targetRevision: main
      path: core/grafana-assets
    - chart: kube-prometheus-stack
      targetRevision: 81.2.1
      repoURL: https://prometheus-community.github.io/helm-charts
      helm:
        releaseName: kube-prometheus-stack
        valuesObject:
          crds:
            updateJob:
              enabled: true
          prometheus:
            prometheusSpec:
              retentionSize: 8GiB
              nodeSelector:
                kubernetes.io/arch: amd64
              podMonitorSelector: { }
              podMonitorSelectorNilUsesHelmValues: false
              podMonitorNamespaceSelector:
                matchLabels:
                  prometheus: enabled
              serviceMonitorSelector: { }
              serviceMonitorSelectorNilUsesHelmValues: false
              serviceMonitorNamespaceSelector:
                matchLabels:
                  prometheus: enabled
          alertmanager:
            alertmanagerSpec:
              nodeSelector:
                kubernetes.io/arch: amd64
          prometheus-node-exporter:
            affinity: {}
          grafana:
            grafana.ini:
              server:
                root_url: https://grafana.x.pmcd.io
            persistence:
              type: pvc
              enabled: true
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              size: 5Gi