apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: seerr
    app.kubernetes.io/name: seerr
  name: seerr
  namespace: media
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: seerr
    app.kubernetes.io/name: seerr
  type: ClusterIP
