apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo
  namespace: argocd
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`argo.x.pmcd.io`)
      kind: Rule
      services:
        - name: argocd-server
          port: 8080
  tls:
    certResolver: pmcdio