apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - httproute.yaml
  - rbac.yaml
  - service.yaml

images:
  - name: dozzle
    newName: amir20/dozzle
    newTag: latest
