apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: hdhr2xmltv
    app.kubernetes.io/name: hdhr2xmltv
  name: hdhr2xmltv
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: hdhr2xmltv
    app.kubernetes.io/name: hdhr2xmltv
  type: ClusterIP
