---
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketid
spec:
  selector:
    matchLabels:
      app: pocketid
  template:
    metadata:
      labels:
        app: pocketid
    spec:
      containers:
        - name: pocketid
          image: pocketid
          ports:
            - name: http
              containerPort: 8080
