apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketid
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - clusterrolebinding.yaml

images:
  - name: pocketid
    newName: ghcr.io/pocket-id/pocket-id
    newTag: v2.2.0
