apiVersion: v1
kind: Service
metadata:
  name: pocketid
  namespace: pocketid
spec:
  selector:
    app.kubernetes.io/instance: pocketid
    app.kubernetes.io/name: pocketid
  ports:
    - name: http
      port: 80
      targetPort: http
