{{- if and .Values.persistence.enabled (eq .Values.persistence.type "smb") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-{{ .Release.Name }}-claim
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeName: smb-{{ .Release.Name }}
  storageClassName: ""
{{- end }}
