{{- if and .Values.persistence.enabled (eq .Values.persistence.type "longhorn") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-{{ .Release.Name }}-data
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
