{{- if .Values.onePassword.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "homelab-app.1pwSecretName" . }}
spec:
  itemPath: {{ .Values.onePassword.itemPath | quote }}
{{- end }}
