apiVersion: v1
kind: Service
metadata:
  name: {{ include "homelab-app.fullname" . }}
  labels:
    {{- include "homelab-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "homelab-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.portName }}
  {{- with .Values.service.extraPorts }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
