apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ia-ignition
    app.kubernetes.io/name: ia-ignition
  name: ia-ignition
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: ia-ignition
      app.kubernetes.io/name: ia-ignition
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ia-ignition
        app.kubernetes.io/name: ia-ignition
    spec:
      initContainers:
        - name: preconfigure
          image: inductiveautomation/ignition:latest
          command:
            - /config/scripts/invoke-args.sh
          args:
            - /config/scripts/seed-data-volume.sh
            - /config/scripts/seed-redundancy.sh
            - /config/scripts/prepare-gan-certificates.sh
            - cp /config/files/logback.xml /data/logback.xml
          volumeMounts:
            - mountPath: /data
              name: appconfig
            - mountPath: /config/files
              name: ignition-config-files
            - mountPath: /config/scripts
              name: ignition-config-scripts
            - mountPath: /run/secrets/gan-tls
              name: gan-tls
            - mountPath: /run/secrets/ignition-gan-ca
              name: ignition-gan-ca
              readOnly: true
      containers:
        - name: ia-ignition
          image: ia-ignition
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ia-ignition-config
            - secretRef:
                name: ia-ignition-1pw
          ports:
            - containerPort: 8088
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - mountPath: /usr/local/bin/ignition/data
              name: appconfig
      volumes:
        - name: appconfig
          persistentVolumeClaim:
            claimName: longhorn-ia-ignition-config
        - name: ignition-config-scripts
          configMap:
            name: ignition-config-scripts
            defaultMode: 0755
        - name: ignition-config-files
          configMap:
            name: ignition-config-files
            defaultMode: 0644
        - name: ignition-gan-ca
          secret:
            secretName: ignition-gan-ca
        - name: gan-tls
          secret:
            secretName: backend-gan-tls