apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ia-ignition
    app.kubernetes.io/name: ia-ignition
  name: ia-ignition
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: ia-ignition
      app.kubernetes.io/name: ia-ignition
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ia-ignition
        app.kubernetes.io/name: ia-ignition
    spec:
      containers:
        - name: ia-ignition
          image: ia-ignition
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 90
            timeoutSeconds: 10
            failureThreshold: 3
#          volumeMounts:
#            - mountPath: /app/users
#              name: appconfig
#              subPath: users
#            - mountPath: /app/data
#              name: appconfig
#              subPath: data
#      volumes:
#        - name: appconfig
#          persistentVolumeClaim:
#            claimName: longhorn-ia-ignition-config