apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ia-ignition
    app.kubernetes.io/name: ia-ignition
  name: ia-ignition
  namespace: default
spec:
  ports:
    - name: http
      port: 8088
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: ia-ignition
    app.kubernetes.io/name: ia-ignition
