apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - configmap.yaml
  - deployment.yaml
  - 1password.secret.yaml
  - podmonitor.yaml

images:
  - name: cloudflared
    newName: cloudflare/cloudflared
    newTag: 2026.2.0

configMapGenerator:
  - name: cloudflared
    namespace: default
    files:
      - config.yaml
