apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - configmap.yaml
  - deployment.yaml
  - external-secret.yaml

images:
  - name: cloudflared
    newName: cloudflare/cloudflared
    newTag: 2025.11.1

configMapGenerator:
  - name: cloudflared
    namespace: default
    files:
      - config.yaml
