apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - pvc.yaml
  - 1password.secret.yaml

images:
  - name: freshrss
    newName: freshrss/freshrss
    newTag: latest
