apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: tronbyt-server
    app.kubernetes.io/name: tronbyt-server
  name: tronbyt-server
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: tronbyt-server
      app.kubernetes.io/name: tronbyt-server
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: tronbyt-server
        app.kubernetes.io/name: tronbyt-server
    spec:
      containers:
        - name: tronbyt-server
          image: tronbyt-server
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: tronbyt-server-config
          ports:
            - containerPort: 8000
              hostPort: 8000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 768Mi
            requests:
              cpu: 35m
              memory: 550Mi
          readinessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - mountPath: /app/users
              name: appconfig
              subPath: users
            - mountPath: /app/data
              name: appconfig
              subPath: data
      volumes:
        - name: appconfig
          persistentVolumeClaim:
            claimName: longhorn-tronbyt-server-config