apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - podmonitor.yaml

images:
  - name: unpoller
    newName: ghcr.io/unpoller/unpoller
    newTag: v2.21.0

