apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: unpoller
    app.kubernetes.io/name: unpoller
  name: unpoller
  namespace: default
spec:
  ports:
    - name: tcp
      port: 9130
      protocol: TCP
      targetPort: tcp
  selector:
    app.kubernetes.io/instance: unpoller
    app.kubernetes.io/name: unpoller
